---
# tasks file for el7_nextcloud

- include: packages_install.yml
  tags:
    - selinux

- name: Copy nginx config
  template:
    src: nextcloud.conf
    dest: /etc/nginx/conf.d/nextcloud.conf
    owner: root
    group: root
    mode: '0644'

- name: remove nginx default config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Copy php-fpm config
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: '0644'

- name: Change php directories permissions
  file:
    path: "{{ item }}"
    group: nginx
  with_items:
    - /var/lib/php/session/
    - /var/lib/php/opcache/
    - /var/lib/php/wsdlcache/

- name: SetUp php.ini
  lineinfile:
    path: /etc/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^memory_limit = .*', line: 'memory_limit = 512M' } 
    - { regexp: '^output_buffering = .*', line: 'output_buffering = Off' } 
    - { regexp: '^max_execution_time = .*', line: 'max_execution_time = 300' } 
    - { regexp: '^post_max_size = .*', line: 'post_max_size = 10240M' } 
    - { regexp: '^upload_max_filesize = .*', line: 'upload_max_filesize = 10240M' } 
    - { regexp: '^max_file_uploads = .*', line: 'max_file_uploads = 200' } 
    - { regexp: 'date.timezone =.*', line: 'date.timezone = {{ date_time_zone }}' } 
    - { regexp: 'session.cookie_secure =.*', line: 'session.cookie_secure = True' } 

- name: Configure redis.conf
  lineinfile:
    path: /etc/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^port .*', line: 'port 0' }
    - { regexp: '^# unixsocket .*', line: 'unixsocket /var/run/redis/redis.sock' }
    - { regexp: '^# unixsocketperm .*', line: 'unixsocketperm 770' }
    - { regexp: '^# maxclients .*', line: 'maxclients 256' }

- name: Allow php to read redis socket
  user:
    name: nginx
    groups: redis,mysql,nfsnobody
    append: yes

- include: mariadb_configure.yml
  tags:
    - mariadb

- name: Enable nginx, php-fpm, db, redis
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - php-fpm
    - mariadb
    - redis

- name: Creates directory for nextcloud data
  file:
    path: /var/www/nextcloud/data
    state: directory
    owner: nginx
    group: nginx
    mode: '0770'
  when: nfs_data_share != "none"

- name: Mount data directory by nfs
  mount:
    path: /var/www/nextcloud/data
    src: "{{ nfs_data_share }}" 
    fstype: nfs
    opts: defaults,relatime,context="system_u:object_r:httpd_sys_rw_content_t:s0"
    state: mounted
  when: nfs_data_share != "none"

- include: nc_install.yml 
  tags:
    - nc_install

- include: selinux.yml
  tags:
    - selinux

- name: Allow http in firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Create nextcloud cronjob
  cron: 
    minute: "*/5" 
    name: "Nextcloud job"
    user: "nginx"
    job: "/var/www/nextcloud/cron.php > /dev/null 2>&1"
