---

- name: Set Bareos repo for RHEL/CentOS
  yum_repository:
    name: bareos
    description: 'bareos repo details'
    baseurl: "http://download.bareos.org/bareos/release/{{ bareos_version | default('latest') }}/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/"
    gpgcheck: yes
    gpgkey: "http://download.bareos.org/bareos/release/{{ bareos_version | default('latest') }}/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/repodata/repomd.xml.key"
    enabled: yes
    state: present
  when: ansible_os_family == 'RedHat'

