---

- name: Restart Bareos-dir service
  service:
    name: bareos-dir
    state: restarted
  delegate_to: '{{ bareos_server_addr }}'

- name: Restart Bareos-fd service
  service:
    name: bareos-fd
    state: restarted
